#!/bin/bash

# load helpers
source ./helpers.sh

# bootstrap installs things.
bot 'joelwmale/dotfiles'

if ask 'This will reset configure defaults and install some useful applications. Are you sure you want to continue?' Y; then
    source ./scripts/defaults.sh
    source ./scripts/install.sh
    source ./scripts/dock.sh
else
    error 'Cancelled...'
fi

bot 'Finished configuring details and installing applications!'

if ask 'You should restart your computer to apply all of the changes. Restart now?' Y; then
    sudo -s shutdown -r now
else
    action 'restarting affected applications'
    for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
        "Dock" "Finder" "Mail" "Messages" "Safari" "SizeUp" "SystemUIServer" \
        "Terminal"; do
        killall "${app}" > /dev/null 2>&1
    done
    ok
fi